#!/bin/sh

# A sample post-deploy hook
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLE (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

# echo "$KAMAL_PERFORMER deployed $KAMAL_VERSION to $KAMAL_DESTINATION in $KAMAL_RUNTIME seconds"

echo "THE PRE CONNECT HOOK IS RUNNING"

ssh root@154.53.46.232 'chmod +x listener.sh'
ssh root@154.53.46.232 './listener.sh'

# Return exit code 0 to prevent kamal from not running the command?
exit 0