# Name of your application. Used to uniquely configure containers.
# service: deanout
service: deployer

# Name of the container image.
image: deanin/linktree_demo

# Deploy to these servers.
servers:
  web:
    hosts:
      - 154.53.46.232
    labels:
      traefik.http.routers.deanout_secure.entrypoints: websecure
      traefik.http.routers.deanout_secure.rule: Host(`deanout.com`)
      traefik.http.routers.deanout_secure.tls: true

# Credentials for your image host.
registry:
  username: deanin
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

accessories:
  game:
    roles:
      - web
    image: itzg/minecraft-server
    options:
      publish:
        - "25565:25565"
    volumes:
      - modpacks:/modpacks
      - data:/data
    env:
      TYPE: FORGE
      VERSION: "1.20.1"
      FORGE_VERSION: "47.2.0"
      EULA: "TRUE"
      MEMORY: "4G"
      MODE: "survival"
      MOTD: "A Minecraft Server"
      PVP: "true"
      OPS: "deaniocom"

    labels:
      traefik.http.routers.minecraft.entrypoints: web
      traefik.http.routers.minecraft.rule: Host(`minecraft.deanout.com`)

traefik:
  options:
    publish:
      - "443:443"
  args:
    entryPoints.websecure.address: ":443"

volumes:
  - "storage:/rails/storage"
  - data:/data